version: "3"
services:
  database:
    restart: always
    image: postgres:10.8-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cranecloud
    ports:
      - "4200:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  crane-mongo-db:
    restart: always
    image: mongo:4.2.3
    container_name: crane-mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: crane
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATA_DIR: /data/db
    ports:
      - "27010:27017"
    volumes:
      - cranemongodbdata:/data/db

  redis:
    image: redis:latest
    container_name: crane-redis-db
    ports:
      - "6379:6379"
    volumes:
      - craneredisdbdata:/data

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ckwagaba/osprey-backend:latest
    container_name: flask-api
    environment:
      KUBE_HOST:
      KUBE_TOKEN:
      KUBE_CERT:
      FLASK_APP_SECRET:
      FLASK_APP_SALT:
      FLASK_VERIFY_SALT:
      APP_MAIL_USERNAME:
      APP_MAIL_PASSWORD:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
      MONGO_URI: ${MONGO_URI:-mongodb://crane:password@crane-mongo-db:27017/admin}
      REDIS_URL: ${REDIS_URL:-redis://crane-redis-db:6379}
      DATABASE_USER: postgres
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database:5432/cranecloud}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI:-postgresql://postgres:postgres@database:5432/cranecloud_test}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database
      - crane-mongo-db
    links:
      - database
      - crane-mongo-db
  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ckwagaba/osprey-backend:latest
    container_name: celery-worker
    command: celery -A server.celery worker --loglevel=info
    environment:
      REDIS_URL: ${REDIS_URL:-redis://crane-redis-db:6379}
      MONGO_URI: mongodb://crane:password@crane-mongo-db:27017/admin
      DATABASE_URI: postgresql://postgres:postgres@database:5432/cranecloud
    ports:
      - "4500:5000"
    volumes:
      - .:/app
    links:
      - database
      - crane-mongo-db
  
volumes:
  db-data:
  cranemongodbdata:
  craneredisdbdata:
