version: "3"
services:
  database:
    restart: always
    image: postgres:10.8-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: cranecloud
    ports:
      - "4200:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  crane-mongo-db:
    restart: always
    image: mongo:4.2.3
    container_name: crane-mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: crane
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGODB_DATA_DIR: /data/db
    ports:
      - "27010:27017"
    volumes:
      - cranemongodbdata:/data/db
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ckwagaba/osprey-backend:latest
    container_name: flask-api
    environment:
      DATABASE_URI:
      FLASK_APP_SECRET:
      KUBE_HOST:
      KUBE_TOKEN:
      KUBE_CERT:
      MONGO_URI: mongodb://crane:${MONGO_DB_PASSWORD}@crane-mongo-db:27017/admin
    ports:
      - "4100:5000"
    volumes:
      - .:/app
    depends_on:
      - database
      - crane-mongo-db
    links:
      - database
      - crane-mongo-db
  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ckwagaba/osprey-backend:latest
    container_name: celery-worker
    command: celery -A server.celery worker
    ports:
      - "4500:5000"
    volumes:
      - .:/app
    links:
      - database
      - crane-mongo-db
  

volumes:
  db-data:
  cranemongodbdata: