"""empty message

Revision ID: 042360d08ad7
Revises: 0c06d8d756b2
Create Date: 2019-06-11 12:09:08.446862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042360d08ad7'
down_revision = '0c06d8d756b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
