"""empty message

Revision ID: 069455f983d0
Revises: c8e98de80756
Create Date: 2022-04-13 21:27:33.070391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069455f983d0'
down_revision = 'c8e98de80756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_record', 'date_created')
    # ### end Alembic commands ###
