"""empty message

Revision ID: 08cf4f847c71
Revises: bad9ee459163
Create Date: 2019-11-07 06:34:30.576834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cf4f847c71'
down_revision = 'bad9ee459163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation_members', 'is_admin')
    # ### end Alembic commands ###
