"""empty message

Revision ID: 0cc131c2513f
Revises: 64081c5f2989
Create Date: 2026-03-17 16:36:26.608525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc131c2513f'
down_revision = '64081c5f2989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('app', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('project', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('user', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'enabled_at')
    op.drop_column('user', 'disabled_reason')
    op.drop_column('user', 'disabled_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'deleted')
    op.drop_column('project', 'enabled_at')
    op.drop_column('project', 'disabled_reason')
    op.drop_column('project', 'disabled_at')
    op.drop_column('project', 'deleted_at')
    op.drop_column('app', 'updated_at')
    op.drop_column('app', 'enabled_at')
    op.drop_column('app', 'disabled_reason')
    op.drop_column('app', 'disabled_at')
    op.drop_column('app', 'deleted_at')
    # ### end Alembic commands ###
