"""empty message

Revision ID: 0f754ff293b0
Revises: 1532e6c6c526
Create Date: 2024-08-16 04:20:56.829214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f754ff293b0'
down_revision = '1532e6c6c526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('is_ai', sa.Boolean(), nullable=True))
    op.add_column('app', sa.Column('is_notebook', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'is_notebook')
    op.drop_column('app', 'is_ai')
    # ### end Alembic commands ###
