"""empty message

Revision ID: 107c713a931d
Revises: c7eb8227cead
Create Date: 2025-04-10 09:24:05.885276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107c713a931d'
down_revision = 'c7eb8227cead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_reminder_sent')
    # ### end Alembic commands ###
