"""empty message

Revision ID: 10f2eb785dc1
Revises: 4a3a5589864b
Create Date: 2021-09-01 11:40:36.585962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10f2eb785dc1'
down_revision = '4a3a5589864b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_members')
    op.drop_table('organisation_admins')
    op.drop_table('namespace')
    op.drop_table('organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_admins',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name='organisation_admins_organisation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='organisation_admins_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='organisation_admins_pkey')
    )
    op.create_table('organisation',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organisation_pkey'),
    sa.UniqueConstraint('name', name='organisation_unique_name'),
    postgresql_ignore_search_path=False
    )
    op.create_table('organisation_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name='organisation_members_organisation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='organisation_members_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='organisation_members_pkey')
    )
    op.create_table('namespace',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('organisation_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name='namespace_organisation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='namespace_pkey'),
    sa.UniqueConstraint('name', name='namespace_unique_name')
    )
    # ### end Alembic commands ###
