"""empty message

Revision ID: 11811049c609
Revises: dfcaa8352aa8
Create Date: 2022-05-27 00:33:08.126765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11811049c609'
down_revision = 'dfcaa8352aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_metrics', sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'billing_metrics', 'billing_invoices', ['invoice_id'], ['id'])
    op.add_column('clusters', sa.Column('prometheus_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'prometheus_url')
    op.drop_constraint(None, 'billing_metrics', type_='foreignkey')
    op.drop_column('billing_metrics', 'invoice_id')
    # ### end Alembic commands ###
