"""empty message

Revision ID: 14b57e5cef21
Revises: 3e2ae22e6c73
Create Date: 2020-08-27 16:21:44.955031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b57e5cef21'
down_revision = '3e2ae22e6c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('registries', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registries', 'date_created')
    op.drop_column('clusters', 'date_created')
    # ### end Alembic commands ###
