"""empty message

Revision ID: 1532e6c6c526
Revises: 824b7f125075
Create Date: 2024-07-18 14:06:18.242951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1532e6c6c526'
down_revision = '824b7f125075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_public')
    # ### end Alembic commands ###
