"""empty message

Revision ID: 1888b16f6b99
Revises: e147b1593a64
Create Date: 2024-02-05 10:31:08.935866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1888b16f6b99'
down_revision = 'e147b1593a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'app', ['alias'])
    op.add_column('clusters', sa.Column(
        'sub_domain', sa.String(), nullable=True))
    op.execute(
        "UPDATE clusters SET sub_domain = 'cranecloud.io' WHERE sub_domain IS NULL")
    op.create_unique_constraint(None, 'clusters', ['host'])
    op.create_unique_constraint(None, 'clusters', ['name'])
    op.create_unique_constraint(None, 'project', ['alias'])
    op.create_unique_constraint(None, 'registries', ['name'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'registries', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'clusters', type_='unique')
    op.drop_constraint(None, 'clusters', type_='unique')
    op.drop_column('clusters', 'sub_domain')
    op.drop_constraint(None, 'app', type_='unique')
    # ### end Alembic commands ###
