"""empty message

Revision ID: 1bf24f39f11e
Revises: 0f754ff293b0
Create Date: 2024-09-24 07:24:40.501265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bf24f39f11e'
down_revision = '0f754ff293b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('running', 'unknown', 'failed', 'down', name='appstatuslist'), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_state')
    # ### end Alembic commands ###
