"""empty message

Revision ID: 25107fdaceee
Revises: 3dd1aeef7d33
Create Date: 2023-09-04 22:51:19.873423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25107fdaceee'
down_revision = '3dd1aeef7d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_payment_details')
    op.add_column('app', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('app', 'disabled')
    op.create_table('user_payment_details',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mobile_money_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_payment_details_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_payment_details_pkey')
    )
    # ### end Alembic commands ###
