"""empty message

Revision ID: 254301cda644
Revises: 10f2eb785dc1
Create Date: 2021-10-27 05:18:31.983068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254301cda644'
down_revision = '10f2eb785dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('organisation', sa.String(), nullable=True))
    op.add_column('project', sa.Column('project_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_type')
    op.drop_column('project', 'organisation')
    # ### end Alembic commands ###
