"""empty message

Revision ID: 25c9d573c1b8
Revises: 
Create Date: 2019-09-11 04:01:22.833414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c9d573c1b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('orgainsation_id', sa.Integer(), nullable=True))
    op.add_column('organisation_members', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organisation_members', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'organisation_members', 'organisation', ['orgainsation_id'], ['id'])
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'verified')
    op.drop_constraint(None, 'organisation_members', type_='foreignkey')
    op.drop_constraint(None, 'organisation_members', type_='foreignkey')
    op.drop_column('organisation_members', 'user_id')
    op.drop_column('organisation_members', 'orgainsation_id')
    # ### end Alembic commands ###
