"""empty message

Revision ID: 27141ac3059a
Revises: 64081c5f2989
Create Date: 2026-03-12 22:44:43.160267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27141ac3059a'
down_revision = '64081c5f2989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('app', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('app', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'updated_at')
    op.drop_column('app', 'enabled_at')
    op.drop_column('app', 'disabled_reason')
    op.drop_column('app', 'disabled_at')
    op.drop_column('app', 'deleted_at')
    # ### end Alembic commands ###
