"""empty message

Revision ID: 2b3ee6d21e36
Revises: b3dbe29d1574
Create Date: 2021-04-06 18:34:09.680589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b3ee6d21e36'
down_revision = 'b3dbe29d1574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_flavour',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_database', sa.Column('database_flavour_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'project_database', 'database_flavour', ['database_flavour_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_database', type_='foreignkey')
    op.drop_column('project_database', 'database_flavour_id')
    op.drop_table('database_flavour')
    # ### end Alembic commands ###
