"""empty message

Revision ID: 301ce942b6c9
Revises: 7e6648315e25
Create Date: 2022-10-10 20:42:54.600728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301ce942b6c9'
down_revision = '7e6648315e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
