"""empty message

Revision ID: 320e4e3242e4
Revises: 8b3d685ec316
Create Date: 2020-03-09 16:59:36.851339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320e4e3242e4'
down_revision = '8b3d685ec316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'description')
    # ### end Alembic commands ###
