"""empty message

Revision ID: 3e2ae22e6c73
Revises: 13c61f38f07e
Create Date: 2020-08-20 11:27:06.700735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2ae22e6c73'
down_revision = '13c61f38f07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date_created')
    op.drop_column('app', 'date_created')
    # ### end Alembic commands ###
