"""empty message

Revision ID: 3fd7a1dd57ff
Revises: a253569a7529
Create Date: 2023-02-16 22:44:58.219044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd7a1dd57ff'
down_revision = 'a253569a7529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'deleted')
    # ### end Alembic commands ###
