"""empty message

Revision ID: 43842373bbdb
Revises: 1888b16f6b99
Create Date: 2024-05-10 18:20:10.714966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43842373bbdb'
down_revision = '1888b16f6b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('app', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('reason', sa.String(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.Column('status', sa.Enum('running', 'unknown',
                                                'failed', name='appstatuslist'), nullable=False),
                    sa.Column('last_check', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['app'], ['app.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_state')
    # ### end Alembic commands ###
