"""empty message

Revision ID: 48742b615ffc
Revises: 4889cc091576
Create Date: 2020-03-10 09:40:30.308935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48742b615ffc'
down_revision = '4889cc091576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_image_key', 'app', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('app_image_key', 'app', ['image'])
    # ### end Alembic commands ###
