"""empty message

Revision ID: 4a3a5589864b
Revises: b3dbe29d1574
Create Date: 2021-04-20 17:38:42.655407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3a5589864b'
down_revision = 'b3dbe29d1574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_database', sa.Column('database_flavour_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_database', 'database_flavour_name')
    # ### end Alembic commands ###
