"""empty message

Revision ID: 4af96cd691c5
Revises: 36da442bc732
Create Date: 2020-04-01 23:59:11.427338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af96cd691c5'
down_revision = '36da442bc732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('alias', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'app', ['alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app', type_='unique')
    op.drop_column('app', 'alias')
    # ### end Alembic commands ###
