"""empty message

Revision ID: 4bd21f73a577
Revises: ce49d174ec3f
Create Date: 2022-08-04 22:01:32.947621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bd21f73a577'
down_revision = 'ce49d174ec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_record_billing_invoice_id_fkey', 'transaction_record', type_='foreignkey')
    op.drop_constraint('billing_metrics_invoice_id_fkey', 'billing_metrics', type_='foreignkey')
    op.alter_column('billing_invoices', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.alter_column('billing_metrics', 'invoice_id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('transaction_record', 'billing_invoice_id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key('billing_metrics_invoice_id_fkey', 'billing_metrics', 'billing_invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('transaction_record_billing_invoice_id_fkey', 'transaction_record', 'billing_invoices', ['billing_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_record_billing_invoice_id_fkey', 'transaction_record', type_='foreignkey')
    op.drop_constraint('billing_metrics_invoice_id_fkey', 'billing_metrics', type_='foreignkey')
    op.alter_column('transaction_record', 'billing_invoice_id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=True)
    op.alter_column('billing_metrics', 'invoice_id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    op.alter_column('billing_invoices', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.create_foreign_key('billing_metrics_invoice_id_fkey', 'billing_metrics', 'billing_invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('transaction_record_billing_invoice_id_fkey', 'transaction_record', 'billing_invoices', ['billing_invoice_id'], ['id'])
    # ### end Alembic commands ###
