"""empty message

Revision ID: 55990e80e47d
Revises: 27141ac3059a
Create Date: 2026-03-12 23:33:31.885197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55990e80e47d'
down_revision = '27141ac3059a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('project', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('disabled_reason', sa.String(), nullable=True))
    op.add_column('user', sa.Column('enabled_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'enabled_at')
    op.drop_column('user', 'disabled_reason')
    op.drop_column('user', 'disabled_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'deleted')
    op.drop_column('project', 'enabled_at')
    op.drop_column('project', 'disabled_reason')
    op.drop_column('project', 'disabled_at')
    op.drop_column('project', 'deleted_at')
    # ### end Alembic commands ###
