"""empty message

Revision ID: 599fbd90e403
Revises: 37a2d9830ebf
Create Date: 2019-09-02 06:45:16.068693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599fbd90e403'
down_revision = '37a2d9830ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
