"""empty message

Revision ID: 5ca7df80b59f
Revises: 011c3345849a
Create Date: 2022-05-04 08:53:42.074660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ca7df80b59f'
down_revision = '011c3345849a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_metrics', sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'billing_metrics', 'billing_invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_metrics', type_='foreignkey')
    op.drop_column('billing_metrics', 'invoice_id')
    # ### end Alembic commands ###
