"""empty message

Revision ID: 5efc1c86f739
Revises: fcdfcb2e70a9
Create Date: 2022-09-16 12:33:56.561176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efc1c86f739'
down_revision = 'fcdfcb2e70a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('amount_promotion_credits', sa.Integer(), nullable=True))
    op.add_column('credits', sa.Column('amount_purchased_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'amount_purchased_credits')
    op.drop_column('credits', 'amount_promotion_credits')
    # ### end Alembic commands ###
