"""empty message

Revision ID: 64081c5f2989
Revises: a49047414055
Create Date: 2025-08-25 08:16:07.562694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64081c5f2989'
down_revision = 'a49047414055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('project_tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag_followers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_followers', 'updated_at')
    op.drop_column('tag', 'updated_at')
    op.drop_column('project_tag', 'updated_at')
    op.drop_column('project', 'updated_at')
    
    # ### end Alembic commands ###
