"""empty message

Revision ID: 64081c5f2989
Revises: a49047414055
Create Date: 2025-08-25 08:16:07.562694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64081c5f2989'
down_revision = 'a49047414055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_database')
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('project_tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag_followers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_followers', 'updated_at')
    op.drop_column('tag', 'updated_at')
    op.drop_column('project_tag', 'updated_at')
    op.drop_column('project', 'updated_at')
    op.create_table('project_database',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('project_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('host', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('database_flavour_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('admin_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_database_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_database_pkey')
    )
    # ### end Alembic commands ###
