"""empty message

Revision ID: 66161dfaf17e
Revises: 3aa80b7de17c
Create Date: 2025-07-10 10:17:01.113567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66161dfaf17e'
down_revision = '3aa80b7de17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('task', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'task')
    # ### end Alembic commands ###
