"""empty message

Revision ID: 6fa9a7629442
Revises: ace66fb69686
Create Date: 2021-12-09 21:21:13.884265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa9a7629442'
down_revision = 'ace66fb69686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('has_custom_domain', sa.Boolean(), nullable=True))
    op.execute('''UPDATE "app" SET has_custom_domain = false; ''')
    op.alter_column('app', 'has_custom_domain', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'has_custom_domain')
    # ### end Alembic commands ###
