"""empty message

Revision ID: 701f36199305
Revises: 1bf24f39f11e
Create Date: 2025-03-05 03:27:46.282625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701f36199305'
down_revision = '1bf24f39f11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('api_type', sa.String(length=256), nullable=True))
    op.add_column('app', sa.Column('is_modal', sa.Boolean(), nullable=True))
    op.add_column('app', sa.Column('model_image_uri', sa.String(length=256), nullable=True))
    op.add_column('app', sa.Column('model_server', sa.String(length=256), nullable=True))
    op.alter_column('app', 'image',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app', 'image',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('app', 'model_server')
    op.drop_column('app', 'model_image_uri')
    op.drop_column('app', 'is_modal')
    op.drop_column('app', 'api_type')
    # ### end Alembic commands ###
