"""empty message

Revision ID: 7a5c2b49d0a8
Revises: c3dbe36bec65
Create Date: 2023-02-16 23:54:18.150739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5c2b49d0a8'
down_revision = 'c3dbe36bec65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('project_database', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_database', 'deleted')
    op.drop_column('project', 'deleted')
    op.drop_column('app', 'deleted')
    # ### end Alembic commands ###
