"""empty message

Revision ID: 7e6648315e25
Revises: 5efc1c86f739
Create Date: 2022-10-10 18:17:14.143630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6648315e25'
down_revision = '5efc1c86f739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('promotion_credits', sa.Integer(), nullable=False))
    op.add_column('credits', sa.Column('purchased_credits', sa.Integer(), nullable=False))
    op.drop_column('credits', 'amount_promotion_credits')
    op.drop_column('credits', 'amount_purchased_credits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('amount_purchased_credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('credits', sa.Column('amount_promotion_credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('credits', 'purchased_credits')
    op.drop_column('credits', 'promotion_credits')
    # ### end Alembic commands ###
