"""empty message

Revision ID: 80df49665332
Revises: ce49d174ec3f
Create Date: 2022-07-27 12:36:12.429505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80df49665332'
down_revision = 'ce49d174ec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('transaction_type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_record', 'transaction_type')
    # ### end Alembic commands ###
