"""empty message

Revision ID: 824070fb93a6
Revises: 4bd21f73a577
Create Date: 2022-08-19 13:11:22.288189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824070fb93a6'
down_revision = '4bd21f73a577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('display_id', sa.String(), server_default=sa.text("concat('CC',to_char(CURRENT_DATE, 'YY'), '-', substring(uuid_generate_v4()::TEXT from 1 for 8))"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_invoices', 'display_id')
    # ### end Alembic commands ###
