"""empty message

Revision ID: 894c7f439421
Revises: 80df49665332
Create Date: 2022-08-18 15:40:04.946568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894c7f439421'
down_revision = '80df49665332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_assignments', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_assignments', 'expiry_date')
    # ### end Alembic commands ###
