"""empty message

Revision ID: 901f11361dc8
Revises: d79958f7d348
Create Date: 2022-06-10 01:02:22.317804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '901f11361dc8'
down_revision = 'd79958f7d348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_record', sa.Column('billing_invoice_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'transaction_record', 'billing_invoices', ['billing_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_record', type_='foreignkey')
    op.drop_column('transaction_record', 'billing_invoice_id')
    # ### end Alembic commands ###
