"""empty message

Revision ID: 9020288abc29
Revises: 9e5db6c0d658
Create Date: 2023-06-19 16:33:16.193323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9020288abc29'
down_revision = '9e5db6c0d658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organisation', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organisation')
    # ### end Alembic commands ###
