"""empty message

Revision ID: 9032e9181ebb
Revises: aeef37c779c1
Create Date: 2022-12-12 12:33:25.152063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9032e9181ebb'
down_revision = 'aeef37c779c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anonymous_user_email_key', 'anonymous_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('anonymous_user_email_key', 'anonymous_user', ['email'])
    # ### end Alembic commands ###
