"""empty message

Revision ID: 9105e64cc3c2
Revises: 9020288abc29
Create Date: 2023-07-26 12:32:54.282313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9105e64cc3c2'
down_revision = '9020288abc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('command', sa.String(length=256), nullable=True))
    op.add_column('app', sa.Column('replicas', sa.Integer(), nullable=True))
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('app', 'replicas')
    op.drop_column('app', 'command')
    # ### end Alembic commands ###
