"""empty message

Revision ID: 97be381a8980
Revises: 1888b16f6b99
Create Date: 2024-06-14 12:16:54.004274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97be381a8980'
down_revision = '1888b16f6b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'pinned')
    # ### end Alembic commands ###
