"""empty message

Revision ID: 9a3b07f3e1f2
Revises: 107c713a931d
Create Date: 2025-04-24 23:00:39.896156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3b07f3e1f2'
down_revision = '107c713a931d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('disabled', sa.Boolean(),
                  server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'disabled')
    # ### end Alembic commands ###
