"""empty message

Revision ID: 9f16888c217a
Revises: 75de150720b3
Create Date: 2020-01-20 19:42:21.364838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f16888c217a'
down_revision = '75de150720b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('org_unique_name', 'role', type_='unique')
    op.drop_constraint('role_uuid_key', 'role', type_='unique')
    op.drop_column('role', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('role_uuid_key', 'role', ['uuid'])
    op.create_unique_constraint('org_unique_name', 'role', ['name'])
    # ### end Alembic commands ###
