"""empty message

Revision ID: a22b8b670f7f
Revises: 43842373bbdb
Create Date: 2024-05-13 17:38:12.249853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22b8b670f7f'
down_revision = '43842373bbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_state', sa.Column('failure_reason', sa.String(), nullable=True))
    op.drop_column('app_state', 'reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_state', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('app_state', 'failure_reason')
    # ### end Alembic commands ###
