"""empty message

Revision ID: a253569a7529
Revises: be2db8257033
Create Date: 2023-02-10 13:27:29.414289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a253569a7529'
down_revision = 'be2db8257033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_database', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_database', 'deleted')
    # ### end Alembic commands ###
