"""empty message

Revision ID: a49047414055
Revises: 66161dfaf17e
Create Date: 2025-07-22 22:31:30.355138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a49047414055'
down_revision = '66161dfaf17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('biography', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'social_links')
    op.drop_column('user', 'biography')
    # ### end Alembic commands ###
