"""empty message

Revision ID: a49047414055
Revises: 66161dfaf17e
Create Date: 2025-07-22 22:31:30.355138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'a49047414055'
down_revision = '66161dfaf17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'biography', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('social_links', postgresql.JSONB(
        astext_type=sa.Text()), nullable=True))

    # Fix duplicate usernames before creating unique constraint
    connection = op.get_bind()

    # Find and fix duplicate usernames
    result = connection.execute(text("""
        WITH duplicate_usernames AS (
            SELECT username, COUNT(*) as count
            FROM "user"
            WHERE username IS NOT NULL AND username != ''
            GROUP BY username
            HAVING COUNT(*) > 1
        ),
        ranked_users AS (
            SELECT u.id, u.username,
                   ROW_NUMBER() OVER (PARTITION BY u.username ORDER BY u.date_created ASC) as rn
            FROM "user" u
            INNER JOIN duplicate_usernames d ON u.username = d.username
        )
        SELECT id, username, rn
        FROM ranked_users
        WHERE rn > 1
        ORDER BY username, rn;
    """))

    duplicates = result.fetchall()

    # Update duplicate usernames by appending a number
    for row in duplicates:
        user_id, original_username, row_number = row
        new_username = f"{original_username}_{row_number}"

        # Ensure the new username is unique
        counter = 1
        while True:
            check_result = connection.execute(text(
                'SELECT COUNT(*) FROM "user" WHERE username = :username'
            ), {"username": new_username})

            if check_result.scalar() == 0:
                break

            counter += 1
            new_username = f"{original_username}_{row_number}_{counter}"

        # Update the username
        connection.execute(text(
            'UPDATE "user" SET username = :new_username WHERE id = :user_id'
        ), {"new_username": new_username, "user_id": user_id})

    # Now create the unique constraint
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'social_links')
    op.drop_column('user', 'biography')
    # ### end Alembic commands ###
