"""empty message

Revision ID: a65c56a954d7
Revises: f866f5fd68eb
Create Date: 2023-09-13 22:09:53.442346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65c56a954d7'
down_revision = 'f866f5fd68eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'admin_disabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('admin_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
