"""empty message

Revision ID: ace66fb69686
Revises: 254301cda644
Create Date: 2021-11-04 12:20:06.882301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace66fb69686'
down_revision = '254301cda644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_beta_user', sa.Boolean(), nullable=True))
    op.execute('''UPDATE "user" SET is_beta_user = false; ''')
    op.alter_column('user', 'is_beta_user', nullable=False)
     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_beta_user')
    # ### end Alembic commands ###
