"""empty message

Revision ID: af2544bf3f4c
Revises: 901f11361dc8
Create Date: 2022-07-15 13:28:38.377098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2544bf3f4c'
down_revision = '901f11361dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('cost_modal_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'cost_modal_url')
    # ### end Alembic commands ###
