"""empty message

Revision ID: b3dbe29d1574
Revises: 891856f04d88
Create Date: 2021-03-16 13:07:22.678064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dbe29d1574'
down_revision = '891856f04d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_database', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_database', 'port')
    # ### end Alembic commands ###
