"""empty message

Revision ID: bc50b6e9a79d
Revises: 1888b16f6b99
Create Date: 2024-06-11 12:26:05.367414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc50b6e9a79d'
down_revision = '1888b16f6b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'pinned')
    # ### end Alembic commands ###
