"""empty message

Revision ID: be2db8257033
Revises: 9032e9181ebb
Create Date: 2023-02-10 10:18:25.945209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2db8257033'
down_revision = '9032e9181ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credits', 'purchased_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credits', 'promotion_credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('app', 'deleted')
    # ### end Alembic commands ###
