"""empty message

Revision ID: c7eb8227cead
Revises: 701f36199305
Create Date: 2025-03-21 21:23:14.130634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7eb8227cead'
down_revision = '701f36199305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('supports_ml', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'supports_ml')
