"""empty message

Revision ID: cbe5ac872bb6
Revises: 48742b615ffc
Create Date: 2020-03-10 21:16:58.522675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe5ac872bb6'
down_revision = '48742b615ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'url')
    # ### end Alembic commands ###
