"""empty message

Revision ID: d37de9184661
Revises: 4f443971b60b
Create Date: 2019-09-15 23:39:29.367667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37de9184661'
down_revision = '4f443971b60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespace', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('namespace_orgainsation_id_fkey', 'namespace', type_='foreignkey')
    op.create_foreign_key(None, 'namespace', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('namespace', 'orgainsation_id')
    op.add_column('organisation_members', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('organisation_members_orgainsation_id_fkey', 'organisation_members', type_='foreignkey')
    op.create_foreign_key(None, 'organisation_members', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('organisation_members', 'orgainsation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('orgainsation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organisation_members', type_='foreignkey')
    op.create_foreign_key('organisation_members_orgainsation_id_fkey', 'organisation_members', 'organisation', ['orgainsation_id'], ['id'])
    op.drop_column('organisation_members', 'organisation_id')
    op.add_column('namespace', sa.Column('orgainsation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'namespace', type_='foreignkey')
    op.create_foreign_key('namespace_orgainsation_id_fkey', 'namespace', 'organisation', ['orgainsation_id'], ['id'])
    op.drop_column('namespace', 'organisation_id')
    # ### end Alembic commands ###
