"""empty message

Revision ID: d79958f7d348
Revises: dfcaa8352aa8
Create Date: 2022-05-31 08:49:10.223755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79958f7d348'
down_revision = 'dfcaa8352aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_invoices', 'date_created')
    # ### end Alembic commands ###
