"""empty message

Revision ID: da1b79f5b466
Revises: 011c3345849a
Create Date: 2022-05-13 11:32:37.698951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1b79f5b466'
down_revision = '011c3345849a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('prometheus_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'prometheus_url')
    # ### end Alembic commands ###
