"""empty message

Revision ID: e147b1593a64
Revises: a65c56a954d7
Create Date: 2023-09-19 22:38:23.327709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e147b1593a64'
down_revision = 'a65c56a954d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('admin_disabled', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('admin_disabled', sa.Boolean(), nullable=True))
    op.add_column('project_database', sa.Column('admin_disabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('admin_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_disabled')
    op.drop_column('project_database', 'admin_disabled')
    op.drop_column('project', 'admin_disabled')
    op.drop_column('app', 'admin_disabled')
    # ### end Alembic commands ###
