"""empty message

Revision ID: e2ea2b41abcb
Revises: 6fa9a7629442
Create Date: 2022-03-25 12:59:20.661208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2ea2b41abcb'
down_revision = '6fa9a7629442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payment_details',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('card_expiry', sa.Date(), nullable=True),
    sa.Column('mobile_money_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_invoices',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('date_cashed', sa.DateTime(), nullable=True),
    sa.Column('is_cashed', sa.Boolean(), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_metrics',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('network', sa.Integer(), nullable=True),
    sa.Column('storage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_metrics')
    op.drop_table('billing_invoices')
    op.drop_table('user_payment_details')
    # ### end Alembic commands ###
