"""empty message

Revision ID: f53de63041ad
Revises: 4af96cd691c5
Create Date: 2020-04-07 23:43:17.318556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53de63041ad'
down_revision = '4af96cd691c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('port', sa.Integer(), nullable=True))
    op.execute("UPDATE app SET port = 80")
    op.alter_column('app', 'port', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'port')
    # ### end Alembic commands ###
