apiVersion: v1
kind: Service
metadata:
  name: {{ include "cranecloud-backend.fullname" . }}-celery
  labels:
    {{- include "cranecloud-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.celery.service.type }}
  ports:
    - port: {{ .Values.celery.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cranecloud-backend.selectorLabels" . | nindent 4 }}
